### ISSUE TITLE
Parallelize download

### ISSUE THREAD

**Issue by alexanderadam** [miry/medup#17]
[As you pointed out](https://github.com/miry/medup/pull/2#issuecomment-573939166), downloading my list can take a while. :wink: 

So I guess this would be a perfect opportunity [to parallelize the download](https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html).

There's also [a good `dev.to` post on this on this](https://dev.to/jgaskins/enabling-crystal-s-new-multicore-support-4l4g).

**Comment by miry** [comment]
Added a small parallization, because there is a limit of number of request per second.
