### ISSUE TITLE
Assets (images) not downloaded

### ISSUE THREAD

**Issue by xamat** [miry/medup#51]
Howdy, I did not see this issue reported anywhere. I tried to download my medium blog and I did get posts (both in bulk or individually), but no assets. On closer look, it seems like images are embedded as data directly on the md, which is not what I was expecting nor how the documentation explains it. Is that a bug or something I am doing wrong?

**Comment by miry** [comment]
@xamat It is a default behavior, but you can save images in seperate file with parameters. Example:

```shell
$ medup @miry --assets-images
```

Also to specify the path of assets, you could use other 2 options:

```
$ medup @miry --assets-images --assets-dir=demo/assets --assets-base-path=/assets
```

I tried to cover some of cases in https://medium.com/notes-and-tips-in-full-stack-development/medup-backups-articles-8bf90179b094

Let me know if I can improve something with docs or command to make those options easy to find.

**Comment by miry** [comment]
Example how to possible to sync Medium articles with Jekyll:

```shell
$ medium @xamat -d jekyll_blog/_posts/ --assets-images --assets-dir=jekyll_blog/assets --assets-base-path=/assets
```

**Comment by miry** [comment]
@xamat here is some examples to README to cover those arguments: https://github.com/miry/medup/pull/52

**Comment by xamat** [comment]
@miry Awesome! That actually worked pretty smoothly now! I will mention you in a post I am about to write about this. Not sure how I feel about the example in the README pointing people to my medium blog though :-)

**Comment by miry** [comment]
@xamat Great. I am glad, that it helped. I updated my PR and merged.
